### ISSUE TITLE
What is the reason to remove first table row from report?

### ISSUE THREAD

**Issue by MaksSlesarenko** [EdisonJpp/react-export-table-to-excel#4]
https://github.com/EdisonJpp/react-export-table-to-excel/blob/c210a163fcc94926b6914bb7982d6fb3e90f20cb/src/hooks/useExcel.ts#L35

**Comment by EdisonJpp** [comment]
Cheers,

it was to remove the header ,

It's already fixed you can see the latest version released ( https://github.com/EdisonJpp/react-export-table-to-excel )
